# Generated by Django 3.2.6 on 2021-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tytuł"),
                ),
                (
                    "author",
                    models.CharField(max_length=255, verbose_name="Autor"),
                ),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data publikacji",
                    ),
                ),
                (
                    "isbn_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Numer ISBN",
                    ),
                ),
                (
                    "pages_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Liczba stron"
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Link do okładki",
                    ),
                ),
                (
                    "publication_language",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Język publikacji",
                    ),
                ),
            ],
        ),
    ]
